version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
      
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./.docker/:/var/lib/postgresql/data